# Generated by Django 5.0.6 on 2025-05-13 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdfsummary',
            name='uploaded_at',
        ),
        migrations.AlterField(
            model_name='pdfsummary',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
